# Generated by Django 4.2.17 on 2025-01-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'картинка', 'verbose_name_plural': 'картинки'},
        ),
    ]
