# Generated by Django 4.2.17 on 2025-01-19 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_description_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'картинка',
                'verbose_name_plural': 'картинки',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
