# Generated by Django 4.2.17 on 2025-01-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_alter_placeimage_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Заголовок'),
        ),
    ]
